# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*
- bugfix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  major: 0
  minor: 2

stages:
- stage: versionNonMaster
  displayName: Versioning (non-master)
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: VersionNonMaster
    displayName: Set version
    variables:
       prpatch: $[counter(variables['system.pullrequest.pullrequestnumber'], 0)]
       brpatch: $[counter(variables['build.sourcebranchname'], 0)]
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(major).$(minor)-PullRequest-$(System.PullRequest.PullRequestNumber).$(prpatch)"
        condition: eq(variables['Build.Reason'], 'PullRequest')
        name: SetPRBuildName
      - bash: |
           echo "##vso[build.updatebuildnumber]$(major).$(minor)-$(Build.SourceBranchName).$(brpatch)"
        condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
        name: SetBranchBuildName
- stage: versionMaster
  displayName: Versioning (master)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:        
  - job: VersionMaster
    displayName: Set version
    variables:
       patch: $[counter(variables['minor'], 0)]
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(major).$(minor).$(patch)"
        name: SetMasterBuildName


- stage: Build
  displayName: Build & package
  condition: always()
  jobs:  
  - job: Build
    displayName: Build, test and publish
    steps:   
      - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/geeksync-server GeekSyncServer/GeekSyncServer.csproj
        displayName: 'Build and publish'
      - task: DotNetCoreCLI@2
        displayName: Unit test
        continueOnError: false
        inputs:
          command: 'test'
          testRunTitle: 'Unit test'
      - script: dotnet pack -p:PackageVersion=$(Build.BuildNumber) --output $(Build.ArtifactStagingDirectory)/nupkgs GeekSyncServer/GeekSyncServer.csproj
        displayName: Create NuGet package
      - task: CopyFiles@2
        displayName: Copy Dockerfile
        inputs:
          contents: Dockerfile
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        displayName: Publish artifacts
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'drop' 

      
